<?php 

/**
 * Filter Escape entries
 * 
 * @param array $data
 * @param string $key1
 * @return string
 */

function Escape($data, $key1)
{
    //  $filterArray[$key1] = filter_var($data[$key1] , FILTER_SANITIZE_EMAIL);
    //      $filterArray[$key1] = addslashes($data[$key1]);
    //   $filterArray[$key1] =  preg_replace ('([^A-Za-z0-9.@])', '', $data[$key1]);
    
    
    $search = array(
        "<a>",
        "</a>",
        "<abbr>",
        "</abbr>",
        "<acronym>",
        "</acronym>",
        "<address>",
        "</address>",
        "<applet>",
        "</applet>",
        "<area>",
        "<b>",
        "</b>",
        "<base>",
        "<basefont>",
        "<bdo>",
        "</bdo>",
        "<big>",
        "</big>",
        "<blockquote>",
        "</blockquote>",
        "<br>",
        "<button>",
        "</button>",
        "<caption>",
        "</caption>",
        "<center>",
        "</center>",
        "<cite>",
        "</cite>",
        "<code>",
        "</code>",
        "<col>",
        "<colgroup>",
        "<dd>",
        "<del>",
        "</del>",
        "<dfn>",
        "</dfn>",
        "<dir>",
        "</dir>",
        "<div>",
        "</div>",
        "<dl>",
        "</dl>",
        "<dt>",
        "<em>",
        "</em>",
        "<fieldset>",
        "</fieldset>",
        "<font>",
        "</font>",
        "<form>",
        "</form>",
        "<frame>",
        "<frameset>",
        "</frameset>",
        "<h1>",
        "</h1>",
        "<h2>",
        "</h2>",
        "<h3>",
        "</h3>",
        "<h4>",
        "</h4>",
        "<h5>",
        "</h5>",
        "<h6>",
        "</h6>",
        "<hr>",
        "<i>",
        "</i>",
        "<iframe>",
        "</iframe>",
        "<img>",
        "<input>",
        "<ins>",
        "</ins>",
        "<isindex>",
        "<kbd>",
        "</kbd>",
        "<label>",
        "</label>",
        "<legend>",
        "</legend>",
        "<li>",
        "<link>",
        "<map>",
        "</map>",
        "<menu>",
        "</menu>",
        "<meta>",
        "<noframes>",
        "</noframes>",
        "<noscript>",
        "</noscript>",
        "<object>",
        "</object>",
        "<ol>",
        "</ol>",
        "<optgroup>",
        "</optgroup>",
        "<option>",
        "<p>",
        "<param>",
        "<pre>",
        "</pre>",
        "<q>",
        "</q>",
        "<s>",
        "</s>",
        "<samp>",
        "</samp>",
        "<script>",
        "</script>",
        "<select>",
        "</select>",
        "<small>",
        "</small>",
        "<span>",
        "</span>",
        "<strike>",
        "</strike>",
        "<strong>",
        "</strong>",
        "<style>",
        "</style>",
        "<sub>",
        "</sub>",
        "<sup>",
        "</sup>",
        "<table>",
        "</table>",
        "<td>",
        "<textarea>",
        "</textarea>",
        "<tfoot>",
        "<th>",
        "<thead>",
        "<title>",
        "</title>",
        "<tr>",
        "<tt>",
        "</tt>",
        "<u>",
        "</u>",
        "<ul>",
        "</ul>",
        "<var>",
        "</var>"
    ); // all string that will be remove
    
    $string  = preg_replace ($search, '', $data[$key1]);
    return $data[$key1];
    
//     return $string; 
}

    