<?php 
$users = $viewData['users'];
?>
<h1 class="page-header">Users</h1>

<a href="/crud/insert">Insert</a>
<div class="table-responsive">
<table class="table table-striped">
    <?php foreach($users as $id => $user):?>
        <tr>
           <?php 
            //$user = explode(",", $user);
            foreach ($user as $value):?>               
                <td><?php echo $value;?></td>
            <?php endforeach; ?>
            <td>
                <a href="/crud/update/id/<?=$id;?>">Update</a> | 
                <a href="/crud/delete/id/<?=$id;?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
</div>